version: "3.9"
services:
  react:
    build: "./plantselector-react"
    restart: always
    container_name: react-client
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - server
  server:
    build: "./plantselector-server"
    restart: always
    container_name: express-server
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    # volumes:
    #   - db-data:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
